# ---------------------------------------------------------------------------
# mod_intro.R — the Intro tab (builder-tabs-a)
#
# Static, always renders: no empty state and no error state (contract J.10).
# Every statistical sentence is the canonical contract J.9 copy, taken from the
# CA_COPY_* constants in helpers.R rather than retyped here, so this tab and
# the Documentation tab can never drift apart.
# ---------------------------------------------------------------------------


#' The three-step strip shown on Intro
#'
#' A compact visual of the published order ① expert judgment → ② visual →
#' ③ quantitative, using the `ca-steps` classes. Every step sits at
#' `data-ca-state="pending"`: Intro describes the method, it does not report on
#' the current dataset, so no step ever shows a verdict here.
#'
#' The per-step sentences are the contract's own: ① is the line J.10 fixes for
#' the expert-judgment section, ② and ③ only say which tab does the work.
#'
#' @return an `htmltools` `<ol class="ca-steps">`
#' @noRd
.intro_steps <- function() {
  step <- function(marker, title, body) {
    htmltools::tags$li(
      class = "ca-step", `data-ca-state` = "pending",
      htmltools::tags$span(class = "ca-step__marker", marker),
      htmltools::tags$span(class = "ca-step__rail"),
      htmltools::tags$div(
        htmltools::tags$h3(class = "ca-step__title", title),
        htmltools::tags$p(class = "ca-step__body", body)
      )
    )
  }

  htmltools::tags$ol(
    class = "ca-steps",
    step(
      "①", "Expert judgment",
      "Yours. Software cannot judge clinical plausibility. This step is a conversation with a clinician."
    ),
    step(
      "②", "Visual assessment",
      "Automated by this app — the Kaplan-Meier curve and its reading guide, on the Data and Qualitative steps."
    ),
    step(
      "③", "Quantitative assessment",
      "Automated by this app — the five diagnostics, on the Quantitative step."
    )
  )
}


#' Intro tab UI
#'
#' Order is fixed by contract J.9: title, the mixture-cure-model copy (which
#' states the three steps and the conjunction rule), the three-step visual, the
#' "what this app does not do" note, the start control, then data and ethics.
#'
#' @param id module id, equal to the nav id `"intro"`
#' @noRd
mod_intro_ui <- function(id) {
  ns <- NS(id)

  htmltools::tags$div(
    class = "ca-section",

    htmltools::tags$h1(class = "ca-section__title", CA_COPY_INTRO_TITLE),

    # Contract J.9, verbatim: what a mixture cure model is, why a plateau is
    # not proof, the three steps, and "a conjunction, not a score".
    htmltools::tags$div(class = "ca-lede", htmltools::HTML(CA_COPY_INTRO_HTML)),

    # The same three steps as a visual, immediately under the rule that governs
    # them.
    ca_card(
      title = "The three-step check",
      lede = "The order below is the order of reasoning. These tabs run ③ before ② only because that is the more convenient order to work in.",
      body = .intro_steps()
    ),

    # Contract J.9, verbatim; repeated on Documentation.
    ca_note("info", CA_COPY_NOT_DO_TITLE, htmltools::HTML(CA_COPY_NOT_DO_HTML)),

    # The start control (J.9): the only interactive element on this tab.
    htmltools::tags$div(
      class = "ca-hero",
      actionButton(ns("to_data"), CA_COPY_INTRO_CTA, class = "btn btn-primary btn-lg")
    ),

    # Data and ethics. Procedural, not statistical: where files go, not what
    # the numbers mean.
    ca_note(
      "info",
      "Data and ethics",
      htmltools::tagList(
        htmltools::tags$p(
          "The built-in examples are public, de-identified datasets distributed with the ",
          htmltools::tags$code("survival"),
          " package, plus four simulated scenarios generated by a script in this repository. No patient-identifiable data ships with this app."
        ),
        htmltools::tags$p(
          "A CSV you upload is read into this R session on this machine only. Nothing is transmitted anywhere, nothing is written to disk by the app, and nothing is stored once the session ends."
        )
      )
    )
  )
}


#' Intro tab server
#'
#' The tab holds no state and reads none: its single behaviour is the start
#' control, which hands navigation back to `app.R` through `go_to()`.
#'
#' @param id module id, `"intro"`
#' @param state the one shared `reactiveValues`; unused here, kept because the
#'   module signature in contract section D is fixed
#' @param go_to the navigation callback from `app.R`
#' @noRd
mod_intro_server <- function(id, state, go_to) {
  moduleServer(id, function(input, output, session) {

    ca_on_click(input, "to_data", function() go_to("data"))

    invisible(NULL)
  })
}
